#!/bin/bash

for x in CROP IRONORE SPEAR AXE SCYTHE MEAT PLANK WATER SAW NO_MATERIAL FISHINGROD BREAD FISH GOLDORE HAMMER GOLD COAL WINE FLOUR IRON PIG PICK BOW TRUNK STONE BLADE GEMS GUN_POWDER HONEY KEG LIQUOR MEAD RICE SULFUR SWORD; do
gnuplot -c script.plot $x $1 $2 $3
done
